### ISSUE TITLE
Unchecked exceptions allowed to happen

### ISSUE THREAD

**Issue by virusdave** [zio/zio-metrics#108]
Currently this library is using a `Ref[CollectorRegistry]` for prometheus metrics, and uses `ref.update(...)` when constructing new metrics.  However, `Ref` only allows pure (non-throwing) operations in the `update()` method.  If you change this to `RefM`, then your `update()` can wrap the unsafe throwable calls like `PCounter.build().register(r)` in a `Task` and your callers can handle them safely.

Easiest way to see this is to create a counter with a `.` in the name.

**Comment by ChallenHB** [comment]
Adding a comment for anyone who ran into this problem and might stumble on this issue. Uncaught exceptions like this are considered defects by the ZIO runtime, so you need to use one of `.catchSomeDefect` or `.catchAllDefects` instead of the other `.catch*` methods.
