### ISSUE TITLE
Port tests to zio-test

### ISSUE THREAD

**Issue by mijicd** [zio/zio-metrics#11]
The current suites written in `testz` should be ported to `zio-test`.

**Comment by z0s0** [comment]
Took this task, going to submit PR this week

**Comment by toxicafunk** [comment]
Awesome! Be sure to ping us on #zio-metrics on ZIO's discord if you have any questions or comments (https://discord.gg/2ccFBr4)

**Comment by toxicafunk** [comment]
Closed by #89
