### ISSUE TITLE
Histogram#time that receives a Task

### ISSUE THREAD

**Issue by renancaju** [zio/zio-metrics#20]
Currently `time` receives a function. It would be handy to have a version o `time` that receives a `Task`.

Regarding the return type, I would argue in favor of including the value of the function along with the duration. 

``` 
def time[A](task: Task[A]): Task[WithTime[A]] = ???

case class WithTime[A](duration: Double, result: A)
```

**Comment by toxicafunk** [comment]
Resolved on v0.0.9
